spring:
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.SQLServer2012Dialect
      ddl-auto: update
    show-sql: true
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=backend;integratedSecurity=false;trustServerCertificate=true;
    username: sa
    password: 'P@ssw0rd'
  security:
    user:
      name: admin
      password: 'P@ssw0rd'
